version: '3.7'
services:
  database:
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'memo_flash_cards'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'